// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ONSdigital/dis-search-algorithm/testset/stream"
	"sync"
)

// Ensure, that ReaderMock does implement stream.Reader.
// If this is not the case, regenerate this file with moq.
var _ stream.Reader[any] = &ReaderMock[any]{}

// ReaderMock is a mock implementation of stream.Reader.
//
//	func TestSomethingThatUsesReader(t *testing.T) {
//
//		// make and configure a mocked stream.Reader
//		mockedReader := &ReaderMock{
//			GetFunc: func(ctx context.Context, id string) (T, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context) ([]T, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedReader in code that requires stream.Reader
//		// and then make assertions.
//
//	}
type ReaderMock[T any] struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (T, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]T, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGet  sync.RWMutex
	lockList sync.RWMutex
}

// Get calls GetFunc.
func (mock *ReaderMock[T]) Get(ctx context.Context, id string) (T, error) {
	if mock.GetFunc == nil {
		panic("ReaderMock.GetFunc: method is nil but Reader.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedReader.GetCalls())
func (mock *ReaderMock[T]) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ReaderMock[T]) List(ctx context.Context) ([]T, error) {
	if mock.ListFunc == nil {
		panic("ReaderMock.ListFunc: method is nil but Reader.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedReader.ListCalls())
func (mock *ReaderMock[T]) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
