// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ONSdigital/dis-search-algorithm/testset/stream"
	"sync"
)

// Ensure, that StreamMock does implement stream.Stream.
// If this is not the case, regenerate this file with moq.
var _ stream.Stream[any] = &StreamMock[any]{}

// StreamMock is a mock implementation of stream.Stream.
//
//	func TestSomethingThatUsesStream(t *testing.T) {
//
//		// make and configure a mocked stream.Stream
//		mockedStream := &StreamMock{
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id string) (T, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context) ([]T, error) {
//				panic("mock out the List method")
//			},
//			PutFunc: func(ctx context.Context, id string, item T) error {
//				panic("mock out the Put method")
//			},
//		}
//
//		// use mockedStream in code that requires stream.Stream
//		// and then make assertions.
//
//	}
type StreamMock[T any] struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (T, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]T, error)

	// PutFunc mocks the Put method.
	PutFunc func(ctx context.Context, id string, item T) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Put holds details about calls to the Put method.
		Put []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Item is the item argument value.
			Item T
		}
	}
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
	lockPut    sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *StreamMock[T]) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("StreamMock.DeleteFunc: method is nil but Stream.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedStream.DeleteCalls())
func (mock *StreamMock[T]) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *StreamMock[T]) Get(ctx context.Context, id string) (T, error) {
	if mock.GetFunc == nil {
		panic("StreamMock.GetFunc: method is nil but Stream.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedStream.GetCalls())
func (mock *StreamMock[T]) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *StreamMock[T]) List(ctx context.Context) ([]T, error) {
	if mock.ListFunc == nil {
		panic("StreamMock.ListFunc: method is nil but Stream.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedStream.ListCalls())
func (mock *StreamMock[T]) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Put calls PutFunc.
func (mock *StreamMock[T]) Put(ctx context.Context, id string, item T) error {
	if mock.PutFunc == nil {
		panic("StreamMock.PutFunc: method is nil but Stream.Put was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		ID   string
		Item T
	}{
		Ctx:  ctx,
		ID:   id,
		Item: item,
	}
	mock.lockPut.Lock()
	mock.calls.Put = append(mock.calls.Put, callInfo)
	mock.lockPut.Unlock()
	return mock.PutFunc(ctx, id, item)
}

// PutCalls gets all the calls that were made to Put.
// Check the length with:
//
//	len(mockedStream.PutCalls())
func (mock *StreamMock[T]) PutCalls() []struct {
	Ctx  context.Context
	ID   string
	Item T
} {
	var calls []struct {
		Ctx  context.Context
		ID   string
		Item T
	}
	mock.lockPut.RLock()
	calls = mock.calls.Put
	mock.lockPut.RUnlock()
	return calls
}
