// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ONSdigital/dis-search-algorithm/testset/stream"
	"sync"
)

// Ensure, that WriterMock does implement stream.Writer.
// If this is not the case, regenerate this file with moq.
var _ stream.Writer[any] = &WriterMock[any]{}

// WriterMock is a mock implementation of stream.Writer.
//
//	func TestSomethingThatUsesWriter(t *testing.T) {
//
//		// make and configure a mocked stream.Writer
//		mockedWriter := &WriterMock{
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			PutFunc: func(ctx context.Context, id string, item T) error {
//				panic("mock out the Put method")
//			},
//		}
//
//		// use mockedWriter in code that requires stream.Writer
//		// and then make assertions.
//
//	}
type WriterMock[T any] struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// PutFunc mocks the Put method.
	PutFunc func(ctx context.Context, id string, item T) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Put holds details about calls to the Put method.
		Put []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Item is the item argument value.
			Item T
		}
	}
	lockDelete sync.RWMutex
	lockPut    sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *WriterMock[T]) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("WriterMock.DeleteFunc: method is nil but Writer.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedWriter.DeleteCalls())
func (mock *WriterMock[T]) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Put calls PutFunc.
func (mock *WriterMock[T]) Put(ctx context.Context, id string, item T) error {
	if mock.PutFunc == nil {
		panic("WriterMock.PutFunc: method is nil but Writer.Put was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		ID   string
		Item T
	}{
		Ctx:  ctx,
		ID:   id,
		Item: item,
	}
	mock.lockPut.Lock()
	mock.calls.Put = append(mock.calls.Put, callInfo)
	mock.lockPut.Unlock()
	return mock.PutFunc(ctx, id, item)
}

// PutCalls gets all the calls that were made to Put.
// Check the length with:
//
//	len(mockedWriter.PutCalls())
func (mock *WriterMock[T]) PutCalls() []struct {
	Ctx  context.Context
	ID   string
	Item T
} {
	var calls []struct {
		Ctx  context.Context
		ID   string
		Item T
	}
	mock.lockPut.RLock()
	calls = mock.calls.Put
	mock.lockPut.RUnlock()
	return calls
}
