// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/ONSdigital/dis-search-algorithm/app"
	"sync"
)

// Ensure, that CSVerMock does implement app.CSVer.
// If this is not the case, regenerate this file with moq.
var _ app.CSVer = &CSVerMock{}

// CSVerMock is a mock implementation of app.CSVer.
//
//	func TestSomethingThatUsesCSVer(t *testing.T) {
//
//		// make and configure a mocked app.CSVer
//		mockedCSVer := &CSVerMock{
//			ReadCSVFunc: func(path string) ([]any, error) {
//				panic("mock out the ReadCSV method")
//			},
//			WriteCSVFunc: func(path string, records []any) error {
//				panic("mock out the WriteCSV method")
//			},
//		}
//
//		// use mockedCSVer in code that requires app.CSVer
//		// and then make assertions.
//
//	}
type CSVerMock struct {
	// ReadCSVFunc mocks the ReadCSV method.
	ReadCSVFunc func(path string) ([]any, error)

	// WriteCSVFunc mocks the WriteCSV method.
	WriteCSVFunc func(path string, records []any) error

	// calls tracks calls to the methods.
	calls struct {
		// ReadCSV holds details about calls to the ReadCSV method.
		ReadCSV []struct {
			// Path is the path argument value.
			Path string
		}
		// WriteCSV holds details about calls to the WriteCSV method.
		WriteCSV []struct {
			// Path is the path argument value.
			Path string
			// Records is the records argument value.
			Records []any
		}
	}
	lockReadCSV  sync.RWMutex
	lockWriteCSV sync.RWMutex
}

// ReadCSV calls ReadCSVFunc.
func (mock *CSVerMock) ReadCSV(path string) ([]any, error) {
	if mock.ReadCSVFunc == nil {
		panic("CSVerMock.ReadCSVFunc: method is nil but CSVer.ReadCSV was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockReadCSV.Lock()
	mock.calls.ReadCSV = append(mock.calls.ReadCSV, callInfo)
	mock.lockReadCSV.Unlock()
	return mock.ReadCSVFunc(path)
}

// ReadCSVCalls gets all the calls that were made to ReadCSV.
// Check the length with:
//
//	len(mockedCSVer.ReadCSVCalls())
func (mock *CSVerMock) ReadCSVCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockReadCSV.RLock()
	calls = mock.calls.ReadCSV
	mock.lockReadCSV.RUnlock()
	return calls
}

// WriteCSV calls WriteCSVFunc.
func (mock *CSVerMock) WriteCSV(path string, records []any) error {
	if mock.WriteCSVFunc == nil {
		panic("CSVerMock.WriteCSVFunc: method is nil but CSVer.WriteCSV was just called")
	}
	callInfo := struct {
		Path    string
		Records []any
	}{
		Path:    path,
		Records: records,
	}
	mock.lockWriteCSV.Lock()
	mock.calls.WriteCSV = append(mock.calls.WriteCSV, callInfo)
	mock.lockWriteCSV.Unlock()
	return mock.WriteCSVFunc(path, records)
}

// WriteCSVCalls gets all the calls that were made to WriteCSV.
// Check the length with:
//
//	len(mockedCSVer.WriteCSVCalls())
func (mock *CSVerMock) WriteCSVCalls() []struct {
	Path    string
	Records []any
} {
	var calls []struct {
		Path    string
		Records []any
	}
	mock.lockWriteCSV.RLock()
	calls = mock.calls.WriteCSV
	mock.lockWriteCSV.RUnlock()
	return calls
}
